version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: veustoreoficial_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: veustoreoficial
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3388:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: